version: "3.9"
services:
  status-state-api:
    build: ./status-state-api
    image: status-state-api
    container_name: status-state-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    expose: 
      - "8080"
  status-state-controller:
    build: ./status-state-controller
    image: status-state-controller
    container_name: status-state-controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    depends_on:
      - "status-state-api"